"""url column for songs model

Revision ID: 7969ccbaa78e
Revises: a8eaa3dd3847
Create Date: 2024-02-06 18:34:31.847941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7969ccbaa78e'
down_revision = 'a8eaa3dd3847'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'url')
    # ### end Alembic commands ###
