"""empty message

Revision ID: e9159bac7132
Revises: bd28d8989243
Create Date: 2024-03-08 01:38:23.905861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9159bac7132'
down_revision = 'bd28d8989243'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('at', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('header', sa.String(), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'users', ['at'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'city')
    op.drop_column('users', 'header')
    op.drop_column('users', 'at')
    # ### end Alembic commands ###