"""empty message

Revision ID: 7c6a07bd2846
Revises: ffdc0a98111c
Create Date: 2024-01-31 18:26:43.323028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c6a07bd2846'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('artist_account', sa.BOOLEAN(), nullable=False))
    op.add_column('users', sa.Column('artist_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_picture', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['artist_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'profile_picture')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'artist_name')
    op.drop_column('users', 'artist_account')
    # ### end Alembic commands ###