"""empty message

Revision ID: bd28d8989243
Revises: f46086dc032d
Create Date: 2024-02-20 17:26:32.247867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd28d8989243'
down_revision = 'f46086dc032d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'artist_account',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'artist_account',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###